### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by sirnacnud** [ChimeHQ/OperationPlus#12]
I see Cocoapods support was removed. Is there any chance it could come back?

**Comment by mattmassicotte** [comment]
Hello!

This isn't the first time that someone's asked about restoring CocoaPods support. I truly feel bad, because I don't want to dictate how you work. In fact, I had an extremely hard time migrating from Carthage to SPM myself. The reason I did that migration, and why I opted to remove CocoaPods was I felt I ultimately had no choice. The entire Apple ecosystem, including Apple themselves are using SPM.

This is particularly painful because I know that mixing CocoaPods and SPM is problematic.

If I can help you get started with SPM I'd be happy to. But, I don't think adding back CocoaPods is a good long-term solution.

**Comment by sirnacnud** [comment]
Thank you for the response, yes the Apple ecosystem does seem to be moving towards SPM, but the project I'm working on is still using Cocoapods.

Thanks for offering to help with the transition, probably for the time being, I will have to maintain a fork with the podspec in it.
